### PR TITLE
Build a Settings Page

### PR DESCRIPTION
**Pull request by Ovifer13**
**Issue #237**
**Description**
The system needs a settings page so users can log out and change configurations inside the platform.

For now I will start by doing the following points
- [x] Add a settings icon to the top right of the navbar
- [x] Clicking the settings icon pushes to /settings
- [x] Add logout button and functionality

### CODE REVIEW

**Comment by otech47** [comment]
https://github.dev/setlife-network/website/blob/develop/src/scripts/api.js

**Comment by otech47** [comment]
Be sure to hide the Settings icon if the user is not logged in

**Comment by otech47** [comment]
SettingsPage should be a PrivateRoute

**Comment by Ovifer13** [comment]
https://github.com/expressjs/cookie-session

**Comment by sofiaromorales** [comment]
Screen Shot 2021-11-29 at 12 33 40 PM

**Review by sofiaromorales — APPROVED** [review]

**Pull request merged**
