### PR TITLE
Build Advanced wallet setup flow UI

### LINKED ISSUE #760: Build Advanced wallet setup flow UI
https://www.figma.com/file/qgGWXmprU7vTv7guzWzvML/Project-Trinary?node-id=4678-22983&t=anstUNWIhOe0x19U-0

TODO:

- [x]  UI
- [x]  Check that the DB model is in place for storing the data
- [x]  Store data in DB

### PR DESCRIPTION
**Pull request by Ovifer13**
**Issue #760**

- [x] Build Advanced wallet setup UI
- [x] Create a new mutation to update or create node data

**Proof**
image
image

### CODE REVIEW

**Comment by sofiaromorales** [comment]
Hi @Ovifer13, some comments:
1. Please make the necessary changes to prepopulate the data in the input fields if the user already has an advanced wallet setup, just like in the simple wallet setup
2. Check the UI fixes I made in [4ba0ded](https://github.com/setlife-network/trinary/pull/806/commits/4ba0ded581442bad3622473bdb8739cf1714d9f2)
3. Resolve conflicts with develop branch

**Review by sofiaromorales — CHANGES_REQUESTED** [review]
Resolve comments pls

**Comment by Ovifer13** [comment]
@sofiaromorales done, now if the user has info it will show in the fields.

**Comment by sofiaromorales** [comment]
@Ovifer13 https://www.loom.com/share/adedf1be62b442d79b9477c608202da6

**Comment by Ovifer13** [comment]
@sofiaromorales changes done, also after implementing the authentication of the LN node we won't have to worry about validations in the backend, because if the API can't make a connection to the node it won't store that data in the database.

**Review by sofiaromorales — APPROVED** [review]

**Pull request merged**
