### PR TITLE
Long project names overfilling boxes

### PR DESCRIPTION
**Pull request by Ovifer13**
**Issue #489**
**Description**
Project names in `AllocationTile.js` and `ProjectTile.js` were overfilling from the boxes.

To fix this problem we can use the _overfill_ prop from the `<Box>` component of material-ui. This prop will make the text inside a Box to hide when it is longer than the box width.
[Display - Material-UI](https://material-ui.com/es/system/display/)

**Proof**
image

### CODE REVIEW

**Comment by sofiarm21** [comment]
@Ovifer13 
Could you make an ellipsis effect for when the project name is too long it doesn't break into another line? so all the boxes would be the same height. This is on `/home/projects`
Screen Shot 2021-08-13 at 9 16 06 AM

**Review by otech47 — CHANGES_REQUESTED** [review]
Agree with this: https://github.com/setlife-network/trinary/pull/493#issuecomment-898454649

**Comment by Ovifer13** [comment]
> @Ovifer13
> Could you make an ellipsis effect for when the project name is too long it doesn't break into another line? so all the boxes would be the same height. This is on `/home/projects`
> Screen Shot 2021-08-13 at 9 16 06 AM

**Update**
image

**Review by sofiarm21 — APPROVED** [review]
@Ovifer13 notice the little change I made in last commit

**Comment by Ovifer13** [comment]
> @Ovifer13 notice the little change I made in last commit

I see, I will do this every time I see code like that. Thank you, Sofia!

**Review by otech47 — APPROVED** [review]

**Pull request merged**
