### PR TITLE
Fix empty client Email

### PR DESCRIPTION
**Pull request by mecoccaro**
**Issue #610**
**Description**

- [x] Should be able to create a client with an empty email field (but the value in the DB should be NULL not an empty string)

- [x] When updating a client who does have an email and clearing out the email field, when saving to the DB it should be a NULL value instead of an empty string

**Implementation proof**
https://www.loom.com/share/12b8be21109447fbb99da8b6826aab97
imagen

### CODE REVIEW

**Review by sofiaromorales — COMMENTED** [review]
@mecoccaro I still cant edit the email into an empty field

**Comment by mecoccaro** [comment]
@sofiaromorales I tested again trying to delete the email from an existing client and it worked, if you can, try again and let me know. Also if @otech47 or @Ovifer13 can test would it be great!

**Comment by Ovifer13** [comment]
@mecoccaro I did a test with a user that already had an email and I was able to edit it with the mail field empty.

**Comment by otech47** [comment]
@Ovifer13 can you take another look at this and make sure it works as expected?

**Comment by Ovifer13** [comment]
@otech47 I'm not getting null on the email field after I edit it as an empty field, want me to fix this?

**Comment by Ovifer13** [comment]
**Implementation proof**
<a href="https://www.loom.com/share/a81bcf81a9b44bacbfad3f47ef36161c">
    <p>Fix empty client Email after editing - Watch Video</p>
    
  </a>

**Review by otech47 — APPROVED** [review]

**Pull request merged**
